on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20.7.0'
      - name: Install yarn
        run: npm install -g yarn
      - name: Check dependencies and build
        run: yarn
      #- name: Run tests
      #  run: yarn test:ci uncomment when tests are implemented
